### ISSUE TITLE
Open graph and Twitter Cards

### ISSUE THREAD

**Issue by HappyDoggo** [RationalWiki/rw-config#12]
A user has suggested at RW:TECH that our links on social media look better. I think we should install [Extension:WikiSEO](https://www.mediawiki.org/wiki/Extension:WikiSEO).

@awbs, I got a github account as you badgered me into.

**Comment by ghost** [comment]
I'm still unsure how installing/including extensions works -- best to spam David Gerard.

**Comment by HappyDoggo** [comment]
@awbs the instructions to install are right there on the extension page.

**Comment by HappyDoggo** [comment]
@davidgerard help us. We have no idea what to do.

**Comment by tstarling** [comment]
As I wrote on RW:TECH just now, I'd rather not install WikiSEO. It is tagged unmaintained, and has not been reviewed for security. Maybe we could have OpenGraphMeta instead, if that suits your needs.

**Comment by tstarling** [comment]
As discussed on the site, we now have Description2 and OpenGraphMeta instead of WikiSEO.
