### ISSUE TITLE
Redirect /wiki/index.php to /w/index.php

### ISSUE THREAD

**Issue by ghost** [RationalWiki/rw-config#16]
I guess at some point in history MW was installed under /wiki, because I've seen old links around that point to something like /wiki/index.php?title=Special%3ALog&type=block or similar.

However, because of the rewrite rules, this just pulls up the [deletion log for index.php](https://rationalwiki.org/wiki/Index.php).

I suggest adding a rule to (hard) redirect all /wiki/index.php[...] URLs to /w/index.php[...] instead.

**Comment by davidgerard** [comment]
Nice idea, but I experimented a bit and I can't come up with a rewriterule that quite does the trick, amongst all the other weird things that happen with /wiki/ ... the present state of things may lack elegance, but at this stage I think it's minor enough we can live with it really.

**Comment by ghost** [comment]
I won't pretend to know the innards of MW, so if you say it's not a simple regex I believe you.

It is true that I've only encountered such links amongst old archives and meta-commentary, so it's not crucial.
